### ISSUE TITLE
Invalid content /en/cardano/get-started/what-is-a-cardano-node/

### ISSUE THREAD

**Issue by ConanF3** [cardano-foundation/testnets-cardano-org#278] opened 2020-08-19 14:21 UTC
**Where does the issue occur?**
Link to the file or location on the website where the issue occurs. Optionally add screenshots for context.

**Describe the issue**
A clear and concise description of what the issue is.

**Expected changes**
A clear and concise description of what you expected to change.

**Additional context**

**Comment by olgahryniuk** [comment] 2021-01-27 12:46
It is not clear what the issue is, this page is up-to-date:
https://developers.cardano.org/en/testnets/cardano/get-started/what-is-a-cardano-node/
If you spot any issues, please create one and specify what exactly should be fixed.
Kind regards.

**Closed by olgahryniuk** 2021-01-27 12:46 UTC
